### ISSUE TITLE
Problem with running the program

### ISSUE THREAD

**Issue by coolfish52** [golddranks/monokakido#3]
I already changed the dictionary name and checked the path is correct.

But I still got the error:
`thread 'main' panicked at 'called Result::unwrap() on an Err value: IOError, src/main.rs:10:49
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
`
Are there any settings should I make it right?

thank you very much

**Comment by golddranks** [comment]
This library is still under development, it's not ready yet.

**Comment by golddranks** [comment]
What dictionary are you trying to open/read?

**Comment by coolfish52** [comment]
Thanks, author.
I am trying to open "COBUILD Advanced Dictionary of English, English/Chinese".
But without luck.

I would like to know if Rust can be converted to python? thank you for your reply.

**Comment by golddranks** [comment]
@coolfish52 I see. I have only tested this code with the following Japanese dictionaries:
- 大辞泉: https://www.monokakido.jp/en/dictionaries/daijisen2/index.html
- SINMEIKAI Japanese Dictionary 8th edition https://www.monokakido.jp/en/dictionaries/smk8/index.html
- NHK Japanese Pronunciation Dictionary https://www.monokakido.jp/en/dictionaries/nhkaccent2/index.html

I recently fixed two bugs I happened to find, but there might be many others lurking, as I haven't been able to tests the dictionaries comprehensively yet. I am planning to continue developing this library and fixing bugs as I go. You can test with the latest version in this repo.

It would be helpful if I could test the code with "COBUILD Advanced Dictionary of English, English/Chinese". Could you consider sending the files to me, zipped? My email is pyry.kontio@drasa.eu. They should be under `/Library/Application Support/AppStoreContent/jp.monokakido.Dictionaries/Products`. I can take a look. (I'll be sure to delete the files afterwards for copyright reasons.)

The code can of course be converted to Python by hand. Are you working in Python? I doubt that's a sensible choice though. It would be better to provide a Python wrapper around the library.

**Comment by golddranks** [comment]
So, turns out this dictionary uses a different format for audio files than the three mentioned above. https://www.monokakido.jp/en/dictionaries/cccad/index.html

Fortunately, the format closely resembles the one used for storing dictionary pages. I think I'll be able to extract the implementation of the format itself, and generalise the code a bit, and then support both formats of audio.
